### ISSUE TITLE
Monkey Mod Loader Crashing when instaling mods

### ISSUE THREAD

**Issue by ManOfMemes** [DeadlyKitten/MonkeModManager#12]
when i try to install mods with the loader the loader crashes halfway in and dosnt even load the mods when i get in game 

any help would be greatly apretiated

**Comment by box4y** [comment]
same

**Comment by dereksuomi** [comment]
same

**Comment by gorillatagMODDER12** [comment]
You need to uninstall and reinstall the mods.

**Comment by Polandv2** [comment]
it dont work
