### ISSUE TITLE
not letting me use the software

### ISSUE THREAD

**Issue by Sirjakeyvr** [DeadlyKitten/MonkeModManager#21]
I am trying to download mods for gorilla tag and I found MonkeModManager and I have downloaded the software and when I try to open the software it pops up with a error and that I need a folder that is called Gorilla Tag.exe so I tried to create a folder that is called Gorilla Tag.exe and it still did not work

**Comment by Donutlord333** [comment]
ur mom

**Comment by DeadlyKitten** [comment]
Gorilla Tag.exe is the game, not a folder. And it's not something you create.
