### ISSUE TITLE
Unable to enable mods again.

### ISSUE THREAD

**Issue by GamerLoganDean** [DeadlyKitten/MonkeModManager#22]
I disabled mods quick to play a few games and when i try to enable them it shows and error and pressing continue does not seem to work either.
![Screenshot 2022-04-11 222357](https://user-images.githubusercontent.com/79916667/162835858-ca1cc37d-e01d-4f6b-9551-2133944a3f16.png)

**Comment by gorillatag121453** [comment]
i want mods all the mods

**Comment by gorillatag121453** [comment]
hi
