### ISSUE TITLE
cant get mods in gorilla tag

### ISSUE THREAD

**Issue by GameMage69** [DeadlyKitten/MonkeModManager#33]
when i launch up gorilla tag i cant do anything on the computer and my mods dont work. i went back to the files and it is all messed up and deleted. 

![Screenshot 2022-06-17 230315](https://user-images.githubusercontent.com/107741683/174423595-a42753ce-7bdb-4c29-aad4-3d8bb133422b.png)

**Comment by edster603** [comment]
porn
