### ISSUE TITLE
doesn't work under linux/wine

### ISSUE THREAD

**Issue by headassbtw** [DeadlyKitten/MonkeModManager#4]
it just doesn't, if there's any logs i can give you, tell me how to get them and i'll send em over

**Comment by KINGKP38** [comment]
every time i try to open the file it says thats not gorilla tag.exe

**Comment by TheDrawingCoder-Gamer** [comment]
Yep, it doesn't work under linux/wine. C# UI apps are always iffy with wine.

**Comment by TheDrawingCoder-Gamer** [comment]
If you two are interested I've been developing a Mod Manager that works on linux and fetches same file
https://github.com/TheDrawingCoder-Gamer/GorillaModManager

**Comment by headassbtw** [comment]
i forgot about this lmao

it's because of how wine handles DLLs, you have to add an override for the dll BepIn uses, just like every other unity modloader

**Comment by TheDrawingCoder-Gamer** [comment]
Yep, that's how i fixed it. I had to set up proton overrides for modding to work.
